export const mockProducts = [
  {
    id: 1,
    name: "Rodillo Quita Pelos Reutilizable",
    price: 19.99,
    originalPrice: 39.99,
    category: "Mascotas",
    image: "/images/prod1_roller_1780528713344.png",
    description: "Elimina fácilmente el pelo de tus mascotas de sofás, camas y ropa. No requiere cintas adhesivas ni baterías.",
    rating: 4.9,
    reviewsCount: 1452,
    scarcityText: "🔥 Solo quedan 4 en stock",
    recentSales: 24,
    features: ["Reutilizable infinito", "Fácil de limpiar", "Ideal para sillones"]
  },
  {
    id: 2,
    name: "Mini Licuadora Portátil Recargable",
    price: 29.99,
    originalPrice: 59.99,
    category: "Cocina",
    image: "/images/prod2_blender_1780528723624.png",
    description: "Prepara tus smoothies favoritos donde sea. Batería USB de larga duración y cuchillas de acero inoxidable.",
    rating: 4.8,
    reviewsCount: 893,
    scarcityText: "⚡ Últimas unidades",
    recentSales: 15,
    features: ["Carga por USB", "Cuchillas de acero", "Batería de larga duración"]
  },
  {
    id: 3,
    name: "Corrector de Postura Magnético",
    price: 24.99,
    originalPrice: 49.99,
    category: "Ropa",
    image: "/images/prod3_posture_1780528733843.png",
    description: "Alivia el dolor de espalda y mejora tu postura con un diseño invisible bajo la ropa y fácil de ajustar.",
    rating: 4.7,
    reviewsCount: 3201,
    scarcityText: "🔥 Alta demanda. ¡Vuela!",
    recentSales: 56,
    features: ["Invisible bajo la ropa", "Ajustable", "Imanes terapéuticos"]
  },
  {
    id: 4,
    name: "Set 12 Utensilios de Silicona",
    price: 34.99,
    originalPrice: 69.99,
    category: "Cocina",
    image: "/images/prod4_utensils_1780528743166.png",
    description: "Anti-adherentes, resistentes al calor y con mangos de madera natural. El set perfecto para cuidar tus sartenes.",
    rating: 4.9,
    reviewsCount: 512,
    scarcityText: "📦 Solo 2 sets disponibles",
    recentSales: 8,
    features: ["Silicona libre de BPA", "Mangos de madera", "Resistentes al calor"]
  },
  {
    id: 5,
    name: "Tira LED Inteligente WiFi (5m)",
    price: 19.99,
    originalPrice: 39.99,
    category: "Gadgets",
    image: "/images/prod5_led_1780528765940.png",
    description: "Controla la iluminación desde tu celular o con comandos de voz (Alexa/Google). Millones de colores disponibles.",
    rating: 4.8,
    reviewsCount: 4210,
    scarcityText: "🔥 Vendido 43 veces hoy",
    recentSales: 43,
    features: ["Control por App", "Sincronización musical", "Compatible con Alexa"]
  },
  {
    id: 6,
    name: "Humidificador Difusor Efecto Fuego",
    price: 39.99,
    originalPrice: 79.99,
    category: "Gadgets",
    image: "/images/prod6_diffuser_1780528775469.png",
    description: "Aromatiza tu espacio y disfruta de una simulación de flama relajante gracias a su iluminación LED integrada.",
    rating: 4.9,
    reviewsCount: 1845,
    scarcityText: "🔥 El más viral de TikTok",
    recentSales: 112,
    features: ["Efecto llama realista", "Silencioso", "Apagado automático"]
  },
  {
    id: 7,
    name: "Cama Relajante Nube para Mascotas",
    price: 45.99,
    originalPrice: 89.99,
    category: "Mascotas",
    image: "/images/prod7_bed_1780528785185.png",
    description: "Diseño ergonómico y material de felpa ultra suave que ayuda a reducir el estrés y la ansiedad de perros y gatos.",
    rating: 4.9,
    reviewsCount: 2214,
    scarcityText: "⏳ Oferta termina pronto",
    recentSales: 34,
    features: ["Ultra suave", "Lavable a máquina", "Base antideslizante"]
  },
  {
    id: 8,
    name: "Faja Cinturilla Térmica Modeladora",
    price: 24.99,
    originalPrice: 49.99,
    category: "Ropa",
    image: "/images/prod8_waist_1780528796021.png",
    description: "Acelera la sudoración y moldea tu figura mientras haces ejercicio o durante tu día a día.",
    rating: 4.6,
    reviewsCount: 943,
    scarcityText: "🔥 Últimas tallas",
    recentSales: 19,
    features: ["Efecto sauna", "Ajustable", "Material transpirable"]
  },
  {
    id: 9,
    name: "Cepillo Secador Voluminizador 3 en 1",
    price: 35.99,
    originalPrice: 75.99,
    category: "Belleza",
    image: "/images/prod9_brush_1780528825106.png",
    description: "Seca, alisa y da volumen en un solo paso. Tecnología iónica para un acabado sin frizz de calidad de salón.",
    rating: 4.8,
    reviewsCount: 5632,
    scarcityText: "⚠️ Inventario bajo",
    recentSales: 89,
    features: ["Tecnología iónica", "3 niveles de calor", "Secado rápido"]
  },
  {
    id: 10,
    name: "Cortador de Verduras Multifunción",
    price: 22.99,
    originalPrice: 44.99,
    category: "Cocina",
    image: "/images/prod10_chopper_1780528834575.png",
    description: "Ahorra tiempo en la cocina. Incluye 7 cuchillas intercambiables de acero inoxidable y contenedor integrado.",
    rating: 4.7,
    reviewsCount: 1205,
    scarcityText: "🔥 28 vendidos hoy",
    recentSales: 28,
    features: ["7 cuchillas", "Acero inoxidable", "Contenedor grande"]
  },
  {
    id: 11,
    name: "Smartwatch Fitness Impermeable IP68",
    price: 49.99,
    originalPrice: 99.99,
    category: "Gadgets",
    image: "/images/prod11_smartwatch_1780528845770.png",
    description: "Monitorea tu frecuencia cardíaca, pasos y sueño. Compatible con iOS y Android. Batería de 7 días de duración.",
    rating: 4.5,
    reviewsCount: 884,
    scarcityText: "⏳ Solo 5 en color negro",
    recentSales: 12,
    features: ["IP68 resistente al agua", "Monitor cardíaco", "Batería de 7 días"]
  },
  {
    id: 12,
    name: "Leggings Push-Up Texturizados",
    price: 27.99,
    originalPrice: 55.99,
    category: "Ropa",
    image: "/images/prod12_leggings_1780528854891.png",
    description: "Levantan y moldean tus glúteos. Tela transpirable y elástica, perfecta para el gimnasio o uso casual.",
    rating: 4.8,
    reviewsCount: 6321,
    scarcityText: "🔥 Producto viral",
    recentSales: 154,
    features: ["Efecto Push-Up", "Anticelulitis", "Tela elástica 4-way"]
  }
];
